### ISSUE TITLE
UPS has only delivered status

### ISSUE THREAD

**Issue by t8ysn** [sauladam/shipment-tracker#25]
The UPS tracking method only shows if delivered or 'unkown'

Is this right?

What part of the code is doing the scraping maybe I can help?

**Comment by sauladam** [comment]
Hey @t8ysn,

sounds like there are some statuses missing. We are actually using this package to track UPS parcels and it seems to work fine for us.

The UPS relevant code lives in [src/Trackers/UPS.php](https://github.com/sauladam/shipment-tracker/blob/master/src/Trackers/UPS.php). 


Could you maybe post some tracking numbers that are not working as expected? 
Also, which version are you using?

Thanks!

**Comment by t8ysn** [comment]
Hi yes, I was able to have a work around yesterday.
What I really wanted was what is $tracker object but unfortunately its a private property. So I had to get the latest event and then typecast into an  array where I then collate all the information I want.

`       
      $dhlTracker = ShipmentTracker::get('UPS');

        /* track with the standard settings */
        $track = $dhlTracker->track('1ZY3TN686803091151','en');
        $track1 = $dhlTracker->track('1ZY3TN686816564947','en');
        $track2 = $dhlTracker->track('1ZY3TN686811247138','en');
        $array = (array) $track->events()[0];
        $array1 = (array) $track1->events()[0];
        $array2 = (array) $track2->events()[0];

        //dd($track->events()[0]->status(),$track1->events()[0],$track2->events()[0]);
        $o = [$array[ "\x00*\x00date"]->toDateTimeString(),$array[ "\x00*\x00status"],$array[ "\x00*\x00location"]];
        $o1 = [$array1[ "\x00*\x00date"]->toDateTimeString(),$array1[ "\x00*\x00status"],$array1[ "\x00*\x00location"]];
        $o2 = [$array2[ "\x00*\x00date"]->toDateTimeString(),$array2[ "\x00*\x00status"],$array1[ "\x00*\x00location"]];
        dd($o,$o1,$o2);
         
        //Outputs
              array:3 [▼
          0 => "2021-02-20 03:45:00"
          1 => "in_transit"
          2 => "Preston, United Kingdom"
        ]
        array:3 [▼
          0 => "2021-02-10 11:24:00"
          1 => "delivered"
          2 => "WIGAN, GB"
        ]
        array:3 [▼
          0 => "2021-01-20 15:11:00"
          1 => "unknown"
          2 => "WIGAN, GB"
        ]
`
But now that I have woke up with a fresh head and reading the documentation again, you've got all this done for us already! My bad!!!

**Comment by sauladam** [comment]
Haha, glad you figured it out! Yeah, most of the properties have accessors, so it shouldn't be too much of a problem getting the data out and transforming it into something useful. For instance:

```php
$tracks = [
    $dhlTracker->track('1ZY3TN686803091151', 'en'),
    $dhlTracker->track('1ZY3TN686816564947', 'en'),
    $dhlTracker->track('1ZY3TN686811247138', 'en'),
];

array_map(function ($track) {
    return [
        'recipient' => $track->getRecipient(),

        'delivered' => $track->delivered(),

        'current' => [
            'date' => $track->latestEvent()->getDate()->toDateTimeString(),
            'status' => $track->latestEvent()->getStatus(),
            'location' => $track->latestEvent()->getLocation(),
        ],

        'history' => array_map(function ($event) {
            return [
                'date' => $event->getDate(),
                'location' => $event->getLocation(),
                'description' => $event->getDescription(),
                'status' => $event->getStatus(),
            ];
        }, $track->events()),
    ];
}, $tracks);
```

Thanks for checking back and have a great day!
